language: node_js
dist: trusty
node_js:
  - "6.10"
addons:
  chrome: stable
before_script:
  - yarn link
script: yarn test
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
